### ISSUE TITLE
Compositor

### ISSUE THREAD

**Issue by joshmyersdean** [TACJu/PartImageNet#10]
Thank you for the great work! May I ask when you plan on releasing the code for Compositor?

**Comment by TACJu** [comment]
Hi, thanks for your interest in our work. We will try to release the code for Compositor this week, and gradually update all the checkpoints after CVPR.

**Comment by baoxiaoyi** [comment]
Hi! May I ask when you plan on releasing the code for Compositor?

**Comment by joshmyersdean** [comment]
Hi @TACJu,

Do you have an updated timeline for releasing compositor?

Thank you!
Josh

**Comment by TACJu** [comment]
Hi Josh,

So sorry for running late, will be out this weekend. Stay tuned!
