### ISSUE TITLE
Implementation of DeepLabV3+

### ISSUE THREAD

**Issue by joshmyersdean** [TACJu/PartImageNet#11]
Thank you for this work! Could you point me to the implementation of deeplab you used for your paper?

**Comment by TACJu** [comment]
Thanks for your interest in our work. We basically just registered PartImageNet in mmsegmentation and ran deeplab for the baseline experiments in this work. If needed, we can open-source the mmsegmentation registration code after CVPR.

**Comment by joshmyersdean** [comment]
Thanks for the response! Would you be able to potentially email me the regisration code ahead of CVPR?

**Comment by TACJu** [comment]
I will try but I can not guarantee to finish it before CVPR. I recommend registering it following https://mmsegmentation.readthedocs.io/en/main/advanced_guides/add_datasets.html.

**Comment by joshmyersdean** [comment]
Hi @TACJu, I am having trouble reproducing your deeplab results (object mIoU for both torch and mmseg is ~50), which I need for CVPR, and was wondering if I could ask some more specific questions over email? My email is josh.myers-dean [at] colorado.edu -- thank you!
