### ISSUE TITLE
Object Class Choices

### ISSUE THREAD

**Issue by joshmyersdean** [TACJu/PartImageNet#13]
Hello!

Do you describe what object categories you chose? For example, looking through the object annotations, it appears that dog gets mapped to multiple class values (e.g., 20, 48, 144). Does this refer to different breeds of dogs?

**Comment by joshmyersdean** [comment]
I just realized that the file names contain the synset for the object so I am closing this issue.

**Comment by PX-Xu** [comment]
Hello, could you please tell me how to map image names to the classes mentioned in README.md?

Also, how do I extract the names of the parts of each object?

<img width="384" height="417" alt="Image" src="https://github.com/user-attachments/assets/fe31eb9f-802b-4fa9-9bb8-ee0c1e5363ca" />
